### ISSUE TITLE
Thoughts on moving from Firebase

### ISSUE THREAD

**Issue by tomopagu** [tomopagu/Doujin-Release-Tracker#33]
Firebase is great yes, however we're not using it to it's fullest by not taking advantage of the real time stuff and it can seem slow to load sometimes. I guess we can just host the JSON ourselves using mongo or something though would this be any quicker I don't know. Maybe add a short cache duration or something too.

**Comment by Tomo-san** [comment]
So uhh yeah, using Laravel(PHP) + Mongo...
